shared:
  output_path: /data/jsy/open-p2p/train_out/wo_state_cond_random_init
  enable_torch_compile: true
  n_seq_timesteps: 128
  frame_height: &frame_height 192
  frame_width: &frame_width 192
  precision: bf16-mixed
  text_tokenizer_config:
    text_tokenizer_name: "gemma"
    model_name_or_path: "checkpoints/embeddinggemma-300M"
    max_position_embeddings: 128
    text_embedding_shape: [1, 768]
    text_annotation_model_version: ["gemini-2.5-flash", "gemini-2.5-flash-thinking-0905"]
  tokenizer:
    type: "conv"
    conv_tokenizer_config:
      num_tokens: 1

inference:
  mouse_sampling_approach: "truncated_normal"

policy_model:
  n_transformer_layers: 10
  n_q_head: 16
  n_kv_head: 16
  n_thinking_tokens: 1
  transformer_dim: &transformer_dim 1024
  mask_block_size: 128
  attention_history_len: [128, 128, 128, 128, 128, 128, 128, 128, 128, 128]
  n_kv_sink_tokens: 0
  model_type: "dense"
  rdt:
    hidden_size: *transformer_dim
    depth: 4
    num_heads: 16
    num_kv_heads: 16
    norm_eps: 1.0e-5
    multiple_of: 256
    ffn_dim_multiplier: null
    use_flash_attn: true
    num_register_tokens: 4
    use_state_condition: false
    use_image_condition: true
    num_train_timesteps: 1000
    num_inference_steps: 100
    flow_match_shift: 3.0
    sigma_max: 1.0
    sigma_min: 0.0029940119760479044
    extra_one_step: true
    action_condition_noise_std: 0.01  # try 0.01-0.02 as a regularization sweep

stage3_finetune:
  optim:
    learning_rate: 1.0e-4
    weight_decay: 1.0e-4
    beta_1: 0.9
    beta_2: 0.999

  validation_step_interval: 500
  n_validation_steps: 2000
  save_every_n_steps: 1000
  n_training_steps: 20000
  accumulate_grad_batches: 1
  freeze_transformer_layers_for_steps: 0

  training_dataset:
    batch_size: 1
    shuffle: true
    dataset_path: "/mnt/nas/datasets5/robotwin_lerobot"
    single_task: "adjust_bottle"
    empty_emb_path: /mnt/nas/datasets5/robotwin_lerobot/empty_emb.pt
    # obs_cam_keys: ["cam_high"]
    obs_cam_keys: ["cam_high", "cam_left_wrist", "cam_right_wrist"]
    multi_view_image_mode: "token_concat"
    # multi_view_image_mode: "first"
    norm_stat:
      q01:
        [-0.06172713458538055, -3.6716461181640625e-05, -0.08783501386642456, -1,
        -1, -1, -1, -0.3547105032205582, -1.3113021850585938e-06,
        -0.11975435614585876, -1, -1, -1, -1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      q99:
        [0.3462600058317184, 0.39966784834861746, 0.14745532035827624, 1, 1, 1, 1,
        0.034201726913452024, 0.39142737388610793, 0.1792279863357542, 1, 1, 1, 1,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        1.0, 1.0]
    image_height: *frame_height
    image_width: *frame_width
    image_frame_stride: 1
    used_action_channel_ids: [0, 1, 2, 3, 4, 5, 6, 28, 7, 8, 9, 10, 11, 12, 13, 29]
    action_dim: 30
    robot_action_dim: 30
    cfg_prob: 0.1
    dataset_init_worker: 4
    dataset_mp_start_method: "spawn"
    dataset_worker_num_workers_per_gpu: 0
    dataset_worker_prefetch_factor: 1
    warn_on_starvation: false
    rand_augmentation:
      fraction_augmented: 1.0
      augmentations:
        - spatial_transform
        - color
        - planckian
        - iso_noise
        - translation
        - random_blur
        - sharpness

  validation_datasets: []

wandb:
  enabled: false
  project: "policy_model"
  exp_name: "delete-me-lerobot-rdt"
